stages:
  - mirror

mirror_to_github:
  stage: mirror
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval "$(ssh-agent -s)"
    - ssh-add "$GITHUB_SSH_KEY"
    - mkdir -p ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
  script:
    - git remote add github ssh://git@github.com/Redegit/sciencemetrics-front.git
    - git push --mirror github
  only:
    - branches
